---
- name: Install package using apt (Debian/Ubuntu)
  hosts: gcp
  become: true
  tasks:
    - name: Install package using apt (Debian/Ubuntu)
      apt:
        name: "{{ package_name }}"
      when: ansible_os_family == "Debian"

- name: Install package using yum (RedHat/CentOS)
  hosts: gcp
  become: true
  tasks:
    - name: Install package using yum (RedHat/CentOS)
      yum:
        name: "{{ package_name }}"
      when: ansible_os_family == "RedHat"
